# Generated by Django 4.2.2 on 2023-07-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0005_remove_account_pin'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transferer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.account'),
        ),
    ]
