# Generated by Django 4.2.2 on 2023-06-27 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='customers',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=None, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=10, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
