# Generated by Django 4.2.2 on 2023-06-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_remove_customers_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(default='', max_length=5),
        ),
    ]
